#index:
#    path: /
#    controller: App\Controller\DefaultController::index
hello_world:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController:templateAction
  defaults:
    template: 'hello_world.html.twig'
